### ISSUE TITLE
[Error] - Fail to run whispers scan in a React project

### ISSUE THREAD

**Issue by lpsm-dev** [Skyscanner/whispers#57]
## Context

I am manually running the CLI to find sensitive data in my project and I hope to automate it in a pipeline later. In the `/code` folder I have the structure of a **react** project

## Problem

After running the command I find a problem similar to the issue #33.

```bash
whispers --rules aws-id,aws-secret,apikey,file-contains-password,file-contains-secret ./code
```

## Prints

**Python Version**:

![image](https://user-images.githubusercontent.com/58797390/117320986-20c97100-ae63-11eb-8dc6-2bd931923e59.png)

**Command error output**:

![image](https://user-images.githubusercontent.com/58797390/117321033-2921ac00-ae63-11eb-9d64-c2e83f6fd464.png)

**Comment by adeptex** [comment]
Hey @lpmatos, thanks for raising! 
Would you be able to provide an example string from your code that is causing it to fail? 
This issue should have been addressed by https://github.com/Skyscanner/whispers/blob/6ff59c984300fdbb32552bcb63f053579cf99da4/whispers/cli.py#L12
I am surprised to see it come up again..

**Comment by lpsm-dev** [comment]
Is there a possibility that the analysis is reading files that are being ignored in .gitignore?

**Comment by adeptex** [comment]
hey @lpmatos, whispers does not check gitignore, otherwise it could miss some juicy things :P 

on the other hand, the expected way to configure whispers would be to create a config file with your exclusions. check the README for details + here is an example of exclusions in the default config: https://github.com/Skyscanner/whispers/blob/6ff59c984300fdbb32552bcb63f053579cf99da4/whispers/config.yml#L5-L24

all things aside, whispers still shouldn't crash like that. would be great to understand what type of file/string is causing this :\
are you scanning a binary file by chance?

**Comment by lpsm-dev** [comment]
@adeptex, cool! That was it! Apparently some build file was being analyzed and this was breaking the execution. I added the 'exclude' and it worked.
